### ISSUE TITLE
轮盘赌插件

### ISSUE THREAD

**Issue by Dishesdog** [FloatTech/ZeroBot-Plugin-Playground#14]

**Comment by guohuiyuan** [comment]
可以实现，不过要想点其他有趣的元素，比如特殊惩罚之类的

**Comment by Dishesdog** [comment]
带禁言的

**Comment by Dishesdog** [comment]
> 可以实现，不过要想点其他有趣的元素，比如特殊惩罚之类的

带禁言的

**Comment by Dishesdog** [comment]
> 可以实现，不过要想点其他有趣的元素，比如特殊惩罚之类的

写好了一版带禁言的 准备推上来

**Comment by guohuiyuan** [comment]
@fumiama 帮他加个编辑权限吧

**Comment by fumiama** [comment]
plz chk mail

**Comment by guohuiyuan** [comment]
这，插件写完了，不在main函数里引用吗

**Comment by guohuiyuan** [comment]
我能改改你的插件吗



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: 菜狗 ***@***.***&gt;
发送时间: 2022年7月13日 15:30
收件人: FloatTech/ZeroBot-Plugin-Playground ***@***.***&gt;
抄送: himawari ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [FloatTech/ZeroBot-Plugin-Playground] 轮盘赌插件 (Issue #14)





  
可以实现，不过要想点其他有趣的元素，比如特殊惩罚之类的
  
写好了一版带禁言的 准备推上来

**Comment by Dishesdog** [comment]
可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月5日(周五) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FloatTech/ZeroBot-Plugin-Playground] 轮盘赌插件 (Issue #14)




 我能改改你的插件吗 
 
 
 
 Sent&amp;nbsp;from&amp;nbsp;my&amp;nbsp;iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 菜狗 ***@***.***&amp;gt; 
 发送时间: 2022年7月13日 15:30 
 收件人: FloatTech/ZeroBot-Plugin-Playground ***@***.***&amp;gt; 
 抄送: himawari ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [FloatTech/ZeroBot-Plugin-Playground] 轮盘赌插件 (Issue #14) 
 
 
 
 
 
    
 可以实现，不过要想点其他有趣的元素，比如特殊惩罚之类的 
    
 写好了一版带禁言的 准备推上来

**Comment by Dishesdog** [comment]
> 我能改改你的插件吗
> 
> 
> 
> Sent&nbsp;from&nbsp;my&nbsp;iPhone
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: 菜狗 ***@***.***&gt;
> 发送时间: 2022年7月13日 15:30
> 收件人: FloatTech/ZeroBot-Plugin-Playground ***@***.***&gt;
> 抄送: himawari ***@***.***&gt;, Comment ***@***.***&gt;
> 主题: Re: [FloatTech/ZeroBot-Plugin-Playground] 轮盘赌插件 (Issue #14)
> 
> 
> 
> 
> 
>   
> 可以实现，不过要想点其他有趣的元素，比如特殊惩罚之类的
>   
> 写好了一版带禁言的 准备推上来
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

这个插件我只是抽时间简单实现了玩法，你可以随意优化更改

**Comment by guohuiyuan** [comment]
可以，牛的

**Comment by Dishesdog** [comment]
可以加上押注玩法，签到给的金币积分什么的可以参与押注，赢者通吃

**Comment by guohuiyuan** [comment]
你这太夸张了，我就改个真心话大冒险




------------------&nbsp;Original message&nbsp;------------------
From: "菜狗"; 
Sendtime: Friday, Aug 5, 2022 7:49 PM
To: "FloatTech/ZeroBot-Plugin-Playground"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [FloatTech/ZeroBot-Plugin-Playground] 轮盘赌插件 (Issue #14)





 
可以加上押注玩法，签到给的金币积分什么的可以参与押注，赢者通吃
