### ISSUE TITLE
肯德基疯狂星期四段子插件

### ISSUE THREAD

**Issue by BigTear** [FloatTech/ZeroBot-Plugin-Playground#60]
肯德基疯狂星期四段子收录 [https://github.com/Nthily/KFC-Crazy-Thursday](https://github.com/Nthily/KFC-Crazy-Thursday)
API [https://kfc-crazy-thursday.vercel.app/api/index](https://kfc-crazy-thursday.vercel.app/api/index)

**Comment by guohuiyuan** [comment]
可以的
