### ISSUE TITLE
申请加入FloatTech，thanks

### ISSUE THREAD

**Issue by count-bt** [FloatTech/ZeroBot-Plugin-Playground#97]

**Comment by count-bt** [comment]
我靠人呢？没人同意吗？

**Comment by MoYoez** [comment]
a 咱去跟源酱说下

**Comment by count-bt** [comment]
> a 咱去跟源酱说下

没在1群

**Comment by MoYoez** [comment]
> > a 咱去跟源酱说下
> 
> 没在1群

咱在一群说过了

不要急 如果想上传的话 走pr也是一样的

**Comment by count-bt** [comment]
> > > a 咱去跟源酱说下
> > 
> > 没在1群
> 
> 咱在一群说过了
> 
> 不要急 如果想上传的话 走pr也是一样的

我是想申请key(˵¯͒〰¯͒˵)

**Comment by MoYoez** [comment]
> > > > a 咱去跟源酱说下
> > > 
> > > 没在1群
> > 
> > 咱在一群说过了
> > 
> > 不要急 如果想上传的话 走pr也是一样的
> 
> 我是想申请key(˵¯͒〰¯͒˵)

进群给他发个红包就行
